name: Trigger auto deployment for meteredbilling-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ gjoshevski-docker-publish ]
    paths:
    - 'src/**'
    - '.github/workflows/meteredbilling-app-AutoDeployTrigger-805019c6-eca0-4b1c-b7dd-1ef7e2b01a63.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: meteredbilling.azurecr.io
          username: ${{ secrets.METEREDBILLINGAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.METEREDBILLINGAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: meteredbilling.azurecr.io/meteredbilling-app:${{ github.sha }}
          file: ./src/Dockerfile
          context: ./src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.METEREDBILLINGAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n meteredbilling-app -g meteredbilling-rg --server meteredbilling.azurecr.io --username  ${{ secrets.METEREDBILLINGAPP_REGISTRY_USERNAME }} --password ${{ secrets.METEREDBILLINGAPP_REGISTRY_PASSWORD }}
            az containerapp update -n meteredbilling-app -g meteredbilling-rg --image meteredbilling.azurecr.io/meteredbilling-app:${{ github.sha }}
